name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: cd aoe-jupyterlab && docker build . --file Dockerfile --tag aoe-jupyterlab:$(date +%s)
